
###GET ALL Gather :
GET http://localhost:3001/api/gather


###GET Single Gather :
GET http://localhost:3001/api/gather/63eb140ce87ee161d0805323


### POST Add to Gather :
## host/api/gather/add/gatherId
POST http://localhost:3001/api/gather/add/63ea2578c2af8bd9e9913907
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTlkNGQ4M2JjMjRmYzVkMzZlZDUwYSIsImlhdCI6MTY3NjI5MjQ0NSwiZXhwIjoxNjc4ODg0NDQ1fQ.QApYG_NK22GRLjWAwh8Vq0KUMWz4-X3Wpyw7VRAs_aA

### POST Leave the Gather :
## host/api/gather/leaveQueue/userId
DELETE http://localhost:3001/api/gather/leaveQueue/63ea2578c2af8bd9e9913907
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTlkNGQ4M2JjMjRmYzVkMzZlZDUwYSIsImlhdCI6MTY3NjI5MjQ0NSwiZXhwIjoxNjc4ODg0NDQ1fQ.QApYG_NK22GRLjWAwh8Vq0KUMWz4-X3Wpyw7VRAs_aA

###POST when gather is started:
POST http://localhost:3001/api/gather/startGather/63ec2012c8eb5ac8fc6b1d4f



### POST Push test players for testing :
## host/api/gather/pushTestPlayers/gatherId
POST http://localhost:3001/api/gather/pushTestPlayers/63ed0158172282d284bd15b4
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZWQwMTFkMTcyMjgyZDI4NGJkMTVhZCIsImlhdCI6MTY3NjQ3NjczOCwiZXhwIjoxNjc5MDY4NzM4fQ.bzvU9zJREfGtwg3WJEUQp_rjMyu_FPhD5MXmcURzEsY

{
 "body":
[
   {"userId": "sadasdasdasdasdas","userName":"Bang0"},
   {"userId": "sadasdasdasduserIdasdas","userName":"Bulbul"},
   {"userId": "sadasdasdasd2asdas","userName":"Mpabe"},
   {"userId": "sadasda11sdasduserIdasdas","userName":"Ronaldo"},
   {"userId": "sadasdasdasd11asdas","userName":"Jacky Chan"},
   {"userId": "sadasdauserId2sdasdasdas","userName":"Hole Nefesh"},
   {"userId": "sadasdasdauserIdsdasdas","userName":"Benzema"},
   {"userId": "sadasdasd44asdasdas","userName":"Caravaliho"},
   {"userId": "sadasdas11dasdasdas","userName":"Bulbul2"},
   {"userId": "sadasdasd444asdasdas","userName":"Homo"}
   ]
}




